from urllib.request import urlopen
import json
def get_json_data(API):
    print('API')
    print(API)
    def get_json_data_dec(func):
        '''
        Get the data returned from a url generated by function
        '''
        def endpoint_request(*args, **kwargs):
            print(*args)
            print(**kwargs)
            print(func(*args, **kwargs))
            response = urlopen(func(*args, **kwargs))
            data = response.read().decode("utf-8")
            return json.loads(data)
        
        return endpoint_request
    return get_json_data_dec