from urllib.request import urlopen
import json

def get_json_data(func):
    '''
    Get the data returned from a url generated by function
    '''
    def endpoint_request():
        response = urlopen(func())
        data = response.read().decode("utf-8")
        return json.loads(data)
    
    return endpoint_request